### ISSUE TITLE
您好，可以提供一份qa_corpus.json数据吗

### ISSUE THREAD

**Issue by ann22** [charlesXu86/Chatbot_Retrieval#7]

**Comment by charlesXu86** [comment]
您好，这个项目最近做了优化，【匹配算法采用了Transformer + onnx】并且迁移到了新的地址：
https://github.com/we-chatter/chatbot_retrieval
=====
在resource下有qa_corpus.json数据

**Comment by ann22** [comment]
不还意思再次打扰您，该链接无法打开

https://github.com/we-chatter/chatbot_retrieval




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "charlesXu86/Chatbot_Retrieval"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午3:04
收件人:&nbsp;"charlesXu86/Chatbot_Retrieval"<Chatbot_Retrieval@noreply.github.com&gt;;
抄送:&nbsp;"候雪飞"<2740738764@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [charlesXu86/Chatbot_Retrieval] 您好，可以提供一份qa_corpus.json数据吗 (#7)





 
您好，这个项目最近做了优化，【匹配算法采用了Transformer + onnx】并且迁移到了新的地址：
 https://github.com/we-chatter/chatbot_retrieval
 
在resource下有qa_corpus.json数据

**Comment by charlesXu86** [comment]
> 不还意思再次打扰您，该链接无法打开 https://github.com/we-chatter/chatbot_retrieval
> […](#)

应该可以了，之前设置成了private，现在改了

**Comment by ann22** [comment]
非常感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "charlesXu86/Chatbot_Retrieval"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午4:37
收件人:&nbsp;"charlesXu86/Chatbot_Retrieval"<Chatbot_Retrieval@noreply.github.com&gt;;
抄送:&nbsp;"候雪飞"<2740738764@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [charlesXu86/Chatbot_Retrieval] 您好，可以提供一份qa_corpus.json数据吗 (#7)





  
不还意思再次打扰您，该链接无法打开 https://github.com/we-chatter/chatbot_retrieval
 …
  
应该可以了，之前设置成了private，现在改了

**Comment by JeremySun1224** [comment]
您好，这个链接 https://github.com/we-chatter/chatbot_retrieval 
还是无法打开，能麻烦您更新一下吗？感激不尽。
